class OddEven{

public static boolean isEven(int num){
return num % 2 == 0;
}

public static void main(String args[]){
if(isEven(90))
System.out.println("Even");
else
System.out.println("Odd");

System.out.println("End of Code");
System.out.println("This code is generated by Nadeem Akhtar");
}
	}
 